import { createMockCollection } from "@/core";

export const reportesMock = createMockCollection([
    { id: "1", elementoId: "4", elemento: "PC Dell OptiPlex", placa: "SENA-TEC-0031", categoria: "Tecnología", ambiente: "Ambiente 101", tipo: "Daño", fecha: "2026-09-15", descripcion: "El equipo presenta problemas al encender.", estado: "Pendiente", reportadoPorId: "4", reportadoPor: "Leanny Parra Moncada" },
    { id: "2", elementoId: "7", elemento: "Mouse Logitech", placa: "SENA-TEC-0034", categoria: "Tecnología", ambiente: "Ambiente 101", tipo: "Daño", fecha: "2026-09-17", descripcion: "El mouse no responde correctamente.", estado: "En revisión", reportadoPorId: "4", reportadoPor: "Leanny Parra Moncada" },
    { id: "3", elementoId: "10", elemento: "Proyector Epson", placa: "SENA-TEC-0060", categoria: "Tecnología", ambiente: "Ambiente 202", tipo: "Daño", fecha: "2026-09-19", descripcion: "La imagen presenta fallas de proyección.", estado: "En proceso", reportadoPorId: "2", reportadoPor: "Santiago Chilito" },
    { id: "4", elementoId: "11", elemento: "Impresora HP LaserJet", placa: "SENA-TEC-0071", categoria: "Oficina", ambiente: "Ambiente 102", tipo: "Falta de insumos", fecha: "2026-09-20", descripcion: "Requiere cambio de tóner.", estado: "Atendido", reportadoPorId: "2", reportadoPor: "Santiago Chilito", respuesta: "Se instaló tóner nuevo." },
    { id: "5", elementoId: "5", elemento: "Monitor Samsung 24\"", placa: "SENA-TEC-0032", categoria: "Tecnología", ambiente: "Ambiente 101", tipo: "Daño", fecha: "2026-09-21", descripcion: "La pantalla presenta parpadeos.", estado: "En proceso", reportadoPorId: "4", reportadoPor: "Leanny Parra Moncada" },
    { id: "6", elementoId: "6", elemento: "Teclado Logitech", placa: "SENA-TEC-0033", categoria: "Tecnología", ambiente: "Ambiente 101", tipo: "Daño", fecha: "2026-09-23", descripcion: "Algunas teclas no funcionan.", estado: "Atendido", reportadoPorId: "4", reportadoPor: "Leanny Parra Moncada" },
    { id: "7", elementoId: "8", elemento: "Portátil Lenovo ThinkPad", placa: "SENA-TEC-0045", categoria: "Tecnología", ambiente: "Ambiente 202", tipo: "Mantenimiento", fecha: "2026-09-24", descripcion: "Requiere mantenimiento preventivo.", estado: "Pendiente", reportadoPorId: "2", reportadoPor: "Santiago Chilito" },
    { id: "8", elementoId: "3", elemento: "Silla de oficina", placa: "SENA-MOB-0114", categoria: "Mobiliario", ambiente: "Ambiente 101", tipo: "Pérdida", fecha: "2026-09-25", descripcion: "No se encuentra en el ambiente asignado.", estado: "En revisión", reportadoPorId: "10", reportadoPor: "Andrés López" },
]);
